openapi: 3.0.3
info:
  title: Analytics Service API
  version: 1.0.0
  description: API для сервиса аналитики
paths:
  /get-metrics:
    get:
      summary: Получить метрики аналитики
      operationId: getMetrics
      parameters:
        - name: from
          in: query
          schema:
            type: string
            format: date-time
          description: Начальная дата для выборки (формат/:/ 2025-05-02 12:34:56)
          required: true
        - name: to
          in: query
          schema:
            type: string
            format: date-time
          description: Конечная дата для выборки (формат/:/ 2025-05-02 12:34:56)
          required: true
        - name: eventType
          in: query
          schema:
            type: string
          description: Тип события для фильтрации
          required: false
        - name: userId
          in: query
          schema:
            type: string
          description: ID пользователя для фильтрации
          required: false
      responses:
        '200':
          description: Метрики успешно получены
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MetricsListResponse'
        '400':
          description: Некорректный запрос
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    EventRequest:
      type: object
      required:
        - eventType
        - userId
      properties:
        eventType:
          type: string
          description: Тип события
        userId:
          type: string
          description: ID пользователя
        timestamp:
          type: string
          format: date-time
          description: Время события (по умолчанию - текущее время)
        durationMs:
          type: integer
          description: Длительность события в миллисекундах
        properties:
          type: object
          additionalProperties:
            type: string
          description: Дополнительные свойства события
    EventResponse:
      type: object
      properties:
        id:
          type: string
          description: ID обработанного события
        status:
          type: string
          description: Статус обработки
    MetricsListResponse:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/Metric'
        totalCount:
          type: integer
          description: Общее количество найденных метрик
        period:
          type: object
          properties:
            from:
              type: string
              format: date-time
            to:
              type: string
              format: date-time
    Metric:
      type: object
      properties:
        id:
          type: string
          description: Уникальный идентификатор метрики
        timestamp:
          type: string
          format: date-time
          description: Временная метка события
        eventType:
          type: string
          description: Тип события
        userId:
          type: string
          description: ID пользователя
        durationMs:
          type: integer
          description: Длительность события в миллисекундах
        properties:
          type: object
          additionalProperties:
            type: string
          description: Дополнительные свойства события
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          description: Сообщение об ошибке
        code:
          type: integer
          description: Код ошибки